# ANN

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.8.0'

In [3]:
dataset = pd.read_csv('D:/Deep_Learning/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
ann = tf.keras.models.Sequential()

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) 

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [16]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy']) 

In [17]:
ann.fit(X_train, y_train, batch_size = 32, epochs =  100)

Epoch 1/100
250/250 [==============================] - 0s 594us/step - loss: 0.5735 - accuracy: 0.7044
Epoch 2/100
250/250 [==============================] - 0s 558us/step - loss: 0.4512 - accuracy: 0.7971
Epoch 3/100
250/250 [==============================] - 0s 565us/step - loss: 0.4259 - accuracy: 0.8119
Epoch 4/100
250/250 [==============================] - 0s 561us/step - loss: 0.4128 - accuracy: 0.8170
Epoch 5/100
250/250 [==============================] - 0s 532us/step - loss: 0.4021 - accuracy: 0.8225
Epoch 6/100
250/250 [==============================] - 0s 524us/step - loss: 0.3925 - accuracy: 0.8300
Epoch 7/100
250/250 [==============================] - 0s 549us/step - loss: 0.3852 - accuracy: 0.8326
Epoch 8/100
250/250 [==============================] - 0s 545us/step - loss: 0.3788 - accuracy: 0.8376
Epoch 9/100
250/250 [==============================] - 0s 528us/step - loss: 0.3735 - accuracy: 0.8393
Epoch 10/100
250/250 [==============================] - 0s 535us/step - l

250/250 [==============================] - 0s 551us/step - loss: 0.3415 - accuracy: 0.8615
Epoch 80/100
250/250 [==============================] - 0s 537us/step - loss: 0.3412 - accuracy: 0.8575
Epoch 81/100
250/250 [==============================] - 0s 547us/step - loss: 0.3411 - accuracy: 0.8596
Epoch 82/100
250/250 [==============================] - 0s 539us/step - loss: 0.3411 - accuracy: 0.8585
Epoch 83/100
250/250 [==============================] - 0s 536us/step - loss: 0.3408 - accuracy: 0.8606
Epoch 84/100
250/250 [==============================] - 0s 541us/step - loss: 0.3408 - accuracy: 0.8596
Epoch 85/100
250/250 [==============================] - 0s 545us/step - loss: 0.3410 - accuracy: 0.8583
Epoch 86/100
250/250 [==============================] - 0s 540us/step - loss: 0.3406 - accuracy: 0.8601
Epoch 87/100
250/250 [==============================] - 0s 544us/step - loss: 0.3405 - accuracy: 0.8591
Epoch 88/100
250/250 [==============================] - 0s 547us/step - loss:

In [18]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))>0.5) 

[[False]]


In [19]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1518   77]
 [ 210  195]]


0.8565